modLoader = "javafml"
loaderVersion = "[45,)"
license = "MIT"
issueTrackerURL = "https://github.com/terrarium-earth/${github_name}/issues"

[[mods]]
modId = "cadmus"
version = "${version}"
displayName = "ModName"
displayURL = "https://modrinth.com/mod/cadmus"
logoFile = "icon.png"
authors = "Alex Nijjar, ThatGravyBoat"
credits = ""
description = "idk"

[[dependencies.cadmus]]
modId = "forge"
mandatory = true
versionRange = "[45,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cadmus]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cadmus]]
modId = "resourcefullib"
mandatory = true
versionRange = "[${resourcefullib_version},)"
ordering = "NONE"
side = "BOTH"